package com.sample.dynamodb.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;

@DynamoDBTable(tableName = "Book")
public class Book {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    private boolean inPublication;
    private String ISBN;
    private String productCategory;
    private String title;
    private int pageCount;
    private double price;

    public Book() {

    }

    public Book( boolean inPublication, String ISBN, String productCategory, String title, int pageCount, double price) {
        this.inPublication = inPublication;
        this.ISBN = ISBN;
        this.productCategory = productCategory;
        this.title = title;
        this.pageCount = pageCount;
        this.price = price;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public boolean isInPublication() {
        return inPublication;
    }

    public void setInPublication(boolean inPublication) {
        this.inPublication = inPublication;
    }

    public String getISBN() {
        return ISBN;
    }

    public void setISBN(String ISBN) {
        this.ISBN = ISBN;
    }

    public String getProductCategory() {
        return productCategory;
    }

    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getPageCount() {
        return pageCount;
    }

    public void setPageCount(int pageCount) {
        this.pageCount = pageCount;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    @Override
    public String toString() {
        return "Book{" +
                "id='" + id + '\'' +
                ", inPublication=" + inPublication +
                ", ISBN='" + ISBN + '\'' +
                ", productCategory='" + productCategory + '\'' +
                ", title='" + title + '\'' +
                ", pageCount=" + pageCount +
                ", price=" + price +
                '}';
    }
}