package com.sample.dynamodb.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;


import java.nio.ByteBuffer;
import java.util.Arrays;


@DynamoDBTable(tableName = "dynamo-enrichment-de-usw2-tst")
public class DynamoEnrichmentDE {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "pk")
    private String id;
    private ByteBuffer pl;

    //@DynamoDBTypeConverted(converter = StringtoBinaryConverter.class)
    private int ttl;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ByteBuffer getPl() {
        return pl;
    }

    public void setPl(ByteBuffer pl) {
        this.pl = pl;
    }

    public int getTtl() {
        return ttl;
    }

    public void setTtl(int ttl) {
        this.ttl = ttl;
    }

    @Override
    public String toString() {
        return "DynamoEnrichmentDE{" +
                "pk='" + id + '\'' +
                ", pl='" + Arrays.toString(pl.array()) + '\'' +
                ", ttl=" + ttl +
                '}';
    }

    public DynamoEnrichmentDE() {
     }

    public DynamoEnrichmentDE(String id, ByteBuffer pl, int ttl) {
        this.id = id;
        this.pl = pl;
        this.ttl = ttl;
    }


}